<?php

declare(strict_types=1);

namespace ImageKit\Responses\Accounts\Origins\OriginGetResponse;

use ImageKit\Core\Attributes\Api;
use ImageKit\Core\Concerns\SdkModel;
use ImageKit\Core\Contracts\BaseModel;
use ImageKit\Responses\Accounts\Origins\OriginGetResponse\AzureBlobStorage\Type;

/**
 * @phpstan-type azure_blob_storage_alias = array{
 *   id: string,
 *   accountName: string,
 *   container: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   type: Type::*,
 *   baseURLForCanonicalHeader?: string,
 * }
 */
final class AzureBlobStorage implements BaseModel
{
    use SdkModel;

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Api]
    public string $id;

    #[Api]
    public string $accountName;

    #[Api]
    public string $container;

    /**
     * Whether to send a Canonical header.
     */
    #[Api]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Api]
    public string $name;

    #[Api]
    public string $prefix;

    /** @var Type::* $type */
    #[Api(enum: Type::class)]
    public string $type;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Api('baseUrlForCanonicalHeader', optional: true)]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new AzureBlobStorage()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * AzureBlobStorage::with(
     *   id: ...,
     *   accountName: ...,
     *   container: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   prefix: ...,
     *   type: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new AzureBlobStorage)
     *   ->withID(...)
     *   ->withAccountName(...)
     *   ->withContainer(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     *   ->withType(...)
     * ```
     */
    public function __construct()
    {
        self::introspect();
        $this->unsetOptionalProperties();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Type::* $type
     */
    public static function with(
        string $id,
        string $accountName,
        string $container,
        string $name,
        string $prefix,
        string $type,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->accountName = $accountName;
        $obj->container = $container;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;
        $obj->name = $name;
        $obj->prefix = $prefix;
        $obj->type = $type;

        null !== $baseURLForCanonicalHeader && $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    public function withAccountName(string $accountName): self
    {
        $obj = clone $this;
        $obj->accountName = $accountName;

        return $obj;
    }

    public function withContainer(string $container): self
    {
        $obj = clone $this;
        $obj->container = $container;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj->name = $name;

        return $obj;
    }

    public function withPrefix(string $prefix): self
    {
        $obj = clone $this;
        $obj->prefix = $prefix;

        return $obj;
    }

    /**
     * @param Type::* $type
     */
    public function withType(string $type): self
    {
        $obj = clone $this;
        $obj->type = $type;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }
}
