<?php

declare(strict_types=1);

namespace ImageKit\Responses\Accounts\Origins\OriginListResponseItem;

use ImageKit\Core\Attributes\Api;
use ImageKit\Core\Concerns\SdkModel;
use ImageKit\Core\Contracts\BaseModel;

/**
 * @phpstan-type google_cloud_storage_gcs_alias = array{
 *   id: string,
 *   bucket: string,
 *   clientEmail: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   type: string,
 *   baseURLForCanonicalHeader?: string,
 * }
 */
final class GoogleCloudStorageGcs implements BaseModel
{
    use SdkModel;

    #[Api]
    public string $type = 'GCS';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Api]
    public string $id;

    #[Api]
    public string $bucket;

    #[Api]
    public string $clientEmail;

    /**
     * Whether to send a Canonical header.
     */
    #[Api]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Api]
    public string $name;

    #[Api]
    public string $prefix;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Api('baseUrlForCanonicalHeader', optional: true)]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new GoogleCloudStorageGcs()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * GoogleCloudStorageGcs::with(
     *   id: ...,
     *   bucket: ...,
     *   clientEmail: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   prefix: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new GoogleCloudStorageGcs)
     *   ->withID(...)
     *   ->withBucket(...)
     *   ->withClientEmail(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     * ```
     */
    public function __construct()
    {
        self::introspect();
        $this->unsetOptionalProperties();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $bucket,
        string $clientEmail,
        string $name,
        string $prefix,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->bucket = $bucket;
        $obj->clientEmail = $clientEmail;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;
        $obj->name = $name;
        $obj->prefix = $prefix;

        null !== $baseURLForCanonicalHeader && $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    public function withBucket(string $bucket): self
    {
        $obj = clone $this;
        $obj->bucket = $bucket;

        return $obj;
    }

    public function withClientEmail(string $clientEmail): self
    {
        $obj = clone $this;
        $obj->clientEmail = $clientEmail;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj->name = $name;

        return $obj;
    }

    public function withPrefix(string $prefix): self
    {
        $obj = clone $this;
        $obj->prefix = $prefix;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }
}
