<?php

declare(strict_types=1);

namespace ImageKit\Responses\Accounts\Origins\OriginUpdateResponse;

use ImageKit\Core\Attributes\Api;
use ImageKit\Core\Concerns\SdkModel;
use ImageKit\Core\Contracts\BaseModel;
use ImageKit\Responses\Accounts\Origins\OriginUpdateResponse\CloudinaryBackup\Type;

/**
 * @phpstan-type cloudinary_backup_alias = array{
 *   id: string,
 *   bucket: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   type: Type::*,
 *   baseURLForCanonicalHeader?: string,
 * }
 */
final class CloudinaryBackup implements BaseModel
{
    use SdkModel;

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Api]
    public string $id;

    /**
     * S3 bucket name.
     */
    #[Api]
    public string $bucket;

    /**
     * Whether to send a Canonical header.
     */
    #[Api]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Api]
    public string $name;

    /**
     * Path prefix inside the bucket.
     */
    #[Api]
    public string $prefix;

    /** @var Type::* $type */
    #[Api(enum: Type::class)]
    public string $type;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Api('baseUrlForCanonicalHeader', optional: true)]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new CloudinaryBackup()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * CloudinaryBackup::with(
     *   id: ...,
     *   bucket: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   prefix: ...,
     *   type: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new CloudinaryBackup)
     *   ->withID(...)
     *   ->withBucket(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     *   ->withType(...)
     * ```
     */
    public function __construct()
    {
        self::introspect();
        $this->unsetOptionalProperties();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Type::* $type
     */
    public static function with(
        string $id,
        string $bucket,
        string $name,
        string $prefix,
        string $type,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->bucket = $bucket;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;
        $obj->name = $name;
        $obj->prefix = $prefix;
        $obj->type = $type;

        null !== $baseURLForCanonicalHeader && $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    /**
     * S3 bucket name.
     */
    public function withBucket(string $bucket): self
    {
        $obj = clone $this;
        $obj->bucket = $bucket;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj->name = $name;

        return $obj;
    }

    /**
     * Path prefix inside the bucket.
     */
    public function withPrefix(string $prefix): self
    {
        $obj = clone $this;
        $obj->prefix = $prefix;

        return $obj;
    }

    /**
     * @param Type::* $type
     */
    public function withType(string $type): self
    {
        $obj = clone $this;
        $obj->type = $type;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }
}
