<?php

declare(strict_types=1);

namespace ImageKit\Responses\Accounts\Origins\OriginUpdateResponse;

use ImageKit\Core\Attributes\Api;
use ImageKit\Core\Concerns\Model;
use ImageKit\Core\Contracts\BaseModel;
use ImageKit\Responses\Accounts\Origins\OriginUpdateResponse\WebFolder\Type;

/**
 * @phpstan-type web_folder_alias = array{
 *   id: string,
 *   baseURL: mixed,
 *   forwardHostHeaderToOrigin: bool,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   type: Type::*,
 *   baseURLForCanonicalHeader?: string,
 * }
 */
final class WebFolder implements BaseModel
{
    use Model;

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Api]
    public string $id;

    /**
     * Root URL for the web folder origin.
     */
    #[Api('baseUrl')]
    public mixed $baseURL;

    /**
     * Forward the Host header to origin?
     */
    #[Api]
    public bool $forwardHostHeaderToOrigin;

    /**
     * Whether to send a Canonical header.
     */
    #[Api]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Api]
    public string $name;

    /** @var Type::* $type */
    #[Api(enum: Type::class)]
    public string $type;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Api('baseUrlForCanonicalHeader', optional: true)]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new WebFolder()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * WebFolder::with(
     *   id: ...,
     *   baseURL: ...,
     *   forwardHostHeaderToOrigin: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   type: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new WebFolder)
     *   ->withID(...)
     *   ->withBaseURL(...)
     *   ->withForwardHostHeaderToOrigin(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withType(...)
     * ```
     */
    public function __construct()
    {
        self::introspect();
        $this->unsetOptionalProperties();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Type::* $type
     */
    public static function with(
        string $id,
        mixed $baseURL,
        string $name,
        string $type,
        bool $forwardHostHeaderToOrigin = false,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->baseURL = $baseURL;
        $obj->forwardHostHeaderToOrigin = $forwardHostHeaderToOrigin;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;
        $obj->name = $name;
        $obj->type = $type;

        null !== $baseURLForCanonicalHeader && $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    /**
     * Root URL for the web folder origin.
     */
    public function withBaseURL(mixed $baseURL): self
    {
        $obj = clone $this;
        $obj->baseURL = $baseURL;

        return $obj;
    }

    /**
     * Forward the Host header to origin?
     */
    public function withForwardHostHeaderToOrigin(
        bool $forwardHostHeaderToOrigin
    ): self {
        $obj = clone $this;
        $obj->forwardHostHeaderToOrigin = $forwardHostHeaderToOrigin;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj->name = $name;

        return $obj;
    }

    /**
     * @param Type::* $type
     */
    public function withType(string $type): self
    {
        $obj = clone $this;
        $obj->type = $type;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->baseURLForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }
}
