<?php

declare(strict_types=1);

namespace Imagekit\Accounts\URLEndpoints;

use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter\Akamai;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter\Cloudinary;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter\Imgix;
use Imagekit\Core\Attributes\Api;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Concerns\SdkResponse;
use Imagekit\Core\Contracts\BaseModel;
use Imagekit\Core\Conversion\Contracts\ResponseConverter;

/**
 * URL‑endpoint object as returned by the API.
 *
 * @phpstan-type URLEndpointResponseShape = array{
 *   id: string,
 *   description: string,
 *   origins: list<string>,
 *   urlPrefix: string,
 *   urlRewriter?: null|Cloudinary|Imgix|Akamai,
 * }
 */
final class URLEndpointResponse implements BaseModel, ResponseConverter
{
    /** @use SdkModel<URLEndpointResponseShape> */
    use SdkModel;

    use SdkResponse;

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    #[Api]
    public string $id;

    /**
     * Description of the URL endpoint.
     */
    #[Api]
    public string $description;

    /**
     * Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     *
     * @var list<string> $origins
     */
    #[Api(list: 'string')]
    public array $origins;

    /**
     * Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).
     */
    #[Api]
    public string $urlPrefix;

    /**
     * Configuration for third-party URL rewriting.
     */
    #[Api(union: URLRewriter::class, optional: true)]
    public Cloudinary|Imgix|Akamai|null $urlRewriter;

    /**
     * `new URLEndpointResponse()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * URLEndpointResponse::with(
     *   id: ..., description: ..., origins: ..., urlPrefix: ...
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new URLEndpointResponse)
     *   ->withID(...)
     *   ->withDescription(...)
     *   ->withOrigins(...)
     *   ->withURLPrefix(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<string> $origins
     * @param Cloudinary|array{
     *   preserveAssetDeliveryTypes: bool, type: 'CLOUDINARY'
     * }|Imgix|array{type: 'IMGIX'}|Akamai|array{type: 'AKAMAI'} $urlRewriter
     */
    public static function with(
        string $id,
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        Cloudinary|array|Imgix|Akamai|null $urlRewriter = null,
    ): self {
        $obj = new self;

        $obj['id'] = $id;
        $obj['description'] = $description;
        $obj['origins'] = $origins;
        $obj['urlPrefix'] = $urlPrefix;

        null !== $urlRewriter && $obj['urlRewriter'] = $urlRewriter;

        return $obj;
    }

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    /**
     * Description of the URL endpoint.
     */
    public function withDescription(string $description): self
    {
        $obj = clone $this;
        $obj['description'] = $description;

        return $obj;
    }

    /**
     * Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     *
     * @param list<string> $origins
     */
    public function withOrigins(array $origins): self
    {
        $obj = clone $this;
        $obj['origins'] = $origins;

        return $obj;
    }

    /**
     * Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).
     */
    public function withURLPrefix(string $urlPrefix): self
    {
        $obj = clone $this;
        $obj['urlPrefix'] = $urlPrefix;

        return $obj;
    }

    /**
     * Configuration for third-party URL rewriting.
     *
     * @param Cloudinary|array{
     *   preserveAssetDeliveryTypes: bool, type: 'CLOUDINARY'
     * }|Imgix|array{type: 'IMGIX'}|Akamai|array{type: 'AKAMAI'} $urlRewriter
     */
    public function withURLRewriter(
        Cloudinary|array|Imgix|Akamai $urlRewriter
    ): self {
        $obj = clone $this;
        $obj['urlRewriter'] = $urlRewriter;

        return $obj;
    }
}
