<?php

declare(strict_types=1);

namespace Imagekit\Accounts\URLEndpoints;

use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter\AkamaiURLRewriter;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter\CloudinaryURLRewriter;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter\ImgixURLRewriter;
use Imagekit\Core\Attributes\Optional;
use Imagekit\Core\Attributes\Required;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * URL‑endpoint object as returned by the API.
 *
 * @phpstan-import-type URLRewriterShape from \Imagekit\Accounts\URLEndpoints\URLEndpointResponse\URLRewriter
 *
 * @phpstan-type URLEndpointResponseShape = array{
 *   id: string,
 *   description: string,
 *   origins: list<string>,
 *   urlPrefix: string,
 *   urlRewriter?: null|URLRewriterShape|CloudinaryURLRewriter|ImgixURLRewriter|AkamaiURLRewriter,
 * }
 */
final class URLEndpointResponse implements BaseModel
{
    /** @use SdkModel<URLEndpointResponseShape> */
    use SdkModel;

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    #[Required]
    public string $id;

    /**
     * Description of the URL endpoint.
     */
    #[Required]
    public string $description;

    /**
     * Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     *
     * @var list<string> $origins
     */
    #[Required(list: 'string')]
    public array $origins;

    /**
     * Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).
     */
    #[Required]
    public string $urlPrefix;

    /**
     * Configuration for third-party URL rewriting.
     */
    #[Optional(union: URLRewriter::class)]
    public CloudinaryURLRewriter|ImgixURLRewriter|AkamaiURLRewriter|null $urlRewriter;

    /**
     * `new URLEndpointResponse()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * URLEndpointResponse::with(
     *   id: ..., description: ..., origins: ..., urlPrefix: ...
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new URLEndpointResponse)
     *   ->withID(...)
     *   ->withDescription(...)
     *   ->withOrigins(...)
     *   ->withURLPrefix(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<string> $origins
     * @param URLRewriterShape $urlRewriter
     */
    public static function with(
        string $id,
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        CloudinaryURLRewriter|array|ImgixURLRewriter|AkamaiURLRewriter|null $urlRewriter = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['description'] = $description;
        $self['origins'] = $origins;
        $self['urlPrefix'] = $urlPrefix;

        null !== $urlRewriter && $self['urlRewriter'] = $urlRewriter;

        return $self;
    }

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Description of the URL endpoint.
     */
    public function withDescription(string $description): self
    {
        $self = clone $this;
        $self['description'] = $description;

        return $self;
    }

    /**
     * Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     *
     * @param list<string> $origins
     */
    public function withOrigins(array $origins): self
    {
        $self = clone $this;
        $self['origins'] = $origins;

        return $self;
    }

    /**
     * Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).
     */
    public function withURLPrefix(string $urlPrefix): self
    {
        $self = clone $this;
        $self['urlPrefix'] = $urlPrefix;

        return $self;
    }

    /**
     * Configuration for third-party URL rewriting.
     *
     * @param URLRewriterShape $urlRewriter
     */
    public function withURLRewriter(
        CloudinaryURLRewriter|array|ImgixURLRewriter|AkamaiURLRewriter $urlRewriter
    ): self {
        $self = clone $this;
        $self['urlRewriter'] = $urlRewriter;

        return $self;
    }
}
