<?php

declare(strict_types=1);

namespace Imagekit\Services\Accounts;

use Imagekit\Accounts\Origins\OriginResponse\AkeneoPim;
use Imagekit\Accounts\Origins\OriginResponse\AzureBlob;
use Imagekit\Accounts\Origins\OriginResponse\CloudinaryBackup;
use Imagekit\Accounts\Origins\OriginResponse\Gcs;
use Imagekit\Accounts\Origins\OriginResponse\S3;
use Imagekit\Accounts\Origins\OriginResponse\S3Compatible;
use Imagekit\Accounts\Origins\OriginResponse\WebFolder;
use Imagekit\Accounts\Origins\OriginResponse\WebProxy;
use Imagekit\Client;
use Imagekit\Core\Exceptions\APIException;
use Imagekit\RequestOptions;
use Imagekit\ServiceContracts\Accounts\OriginsContract;

final class OriginsService implements OriginsContract
{
    /**
     * @api
     */
    public OriginsRawService $raw;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new OriginsRawService($client);
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Creates a new origin and returns the origin object.
     *
     * @param string $accessKey access key for the bucket
     * @param string $name display name of the origin
     * @param string $secretKey secret key for the bucket
     * @param string $endpoint custom S3-compatible endpoint
     * @param string $baseURL akeneo instance base URL
     * @param string $clientID akeneo API client ID
     * @param string $clientSecret akeneo API client secret
     * @param string $password akeneo API password
     * @param string $username akeneo API username
     * @param 'AKENEO_PIM' $type
     * @param string $baseURLForCanonicalHeader URL used in the Canonical header (if enabled)
     * @param bool $includeCanonicalHeader whether to send a Canonical header
     * @param bool $s3ForcePathStyle Use path-style S3 URLs?
     * @param bool $forwardHostHeaderToOrigin Forward the Host header to origin?
     *
     * @throws APIException
     */
    public function create(
        string $accessKey,
        string $bucket,
        string $name,
        string $secretKey,
        string $endpoint,
        string $baseURL,
        string $clientEmail,
        string $privateKey,
        string $accountName,
        string $container,
        string $sasToken,
        string $clientID,
        string $clientSecret,
        string $password,
        string $username,
        string $type = 'AKENEO_PIM',
        ?string $baseURLForCanonicalHeader = null,
        bool $includeCanonicalHeader = false,
        string $prefix = '',
        bool $s3ForcePathStyle = false,
        bool $forwardHostHeaderToOrigin = false,
        ?RequestOptions $requestOptions = null,
    ): S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|Gcs|AzureBlob|AkeneoPim {
        $params = [
            'accessKey' => $accessKey,
            'bucket' => $bucket,
            'name' => $name,
            'secretKey' => $secretKey,
            'type' => $type,
            'baseURLForCanonicalHeader' => $baseURLForCanonicalHeader,
            'includeCanonicalHeader' => $includeCanonicalHeader,
            'prefix' => $prefix,
            'endpoint' => $endpoint,
            's3ForcePathStyle' => $s3ForcePathStyle,
            'baseURL' => $baseURL,
            'forwardHostHeaderToOrigin' => $forwardHostHeaderToOrigin,
            'clientEmail' => $clientEmail,
            'privateKey' => $privateKey,
            'accountName' => $accountName,
            'container' => $container,
            'sasToken' => $sasToken,
            'clientID' => $clientID,
            'clientSecret' => $clientSecret,
            'password' => $password,
            'username' => $username,
        ];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->create(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Updates the origin identified by `id` and returns the updated origin object.
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     * @param string $accessKey access key for the bucket
     * @param string $name display name of the origin
     * @param string $secretKey secret key for the bucket
     * @param string $endpoint custom S3-compatible endpoint
     * @param string $baseURL akeneo instance base URL
     * @param string $clientID akeneo API client ID
     * @param string $clientSecret akeneo API client secret
     * @param string $password akeneo API password
     * @param string $username akeneo API username
     * @param 'AKENEO_PIM' $type
     * @param string $baseURLForCanonicalHeader URL used in the Canonical header (if enabled)
     * @param bool $includeCanonicalHeader whether to send a Canonical header
     * @param bool $s3ForcePathStyle Use path-style S3 URLs?
     * @param bool $forwardHostHeaderToOrigin Forward the Host header to origin?
     *
     * @throws APIException
     */
    public function update(
        string $id,
        string $accessKey,
        string $bucket,
        string $name,
        string $secretKey,
        string $endpoint,
        string $baseURL,
        string $clientEmail,
        string $privateKey,
        string $accountName,
        string $container,
        string $sasToken,
        string $clientID,
        string $clientSecret,
        string $password,
        string $username,
        string $type = 'AKENEO_PIM',
        ?string $baseURLForCanonicalHeader = null,
        bool $includeCanonicalHeader = false,
        string $prefix = '',
        bool $s3ForcePathStyle = false,
        bool $forwardHostHeaderToOrigin = false,
        ?RequestOptions $requestOptions = null,
    ): S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|Gcs|AzureBlob|AkeneoPim {
        $params = [
            'accessKey' => $accessKey,
            'bucket' => $bucket,
            'name' => $name,
            'secretKey' => $secretKey,
            'type' => $type,
            'baseURLForCanonicalHeader' => $baseURLForCanonicalHeader,
            'includeCanonicalHeader' => $includeCanonicalHeader,
            'prefix' => $prefix,
            'endpoint' => $endpoint,
            's3ForcePathStyle' => $s3ForcePathStyle,
            'baseURL' => $baseURL,
            'forwardHostHeaderToOrigin' => $forwardHostHeaderToOrigin,
            'clientEmail' => $clientEmail,
            'privateKey' => $privateKey,
            'accountName' => $accountName,
            'container' => $container,
            'sasToken' => $sasToken,
            'clientID' => $clientID,
            'clientSecret' => $clientSecret,
            'password' => $password,
            'username' => $username,
        ];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->update($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Returns an array of all configured origins for the current account.
     *
     * @return list<S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|Gcs|AzureBlob|AkeneoPim>
     *
     * @throws APIException
     */
    public function list(?RequestOptions $requestOptions = null): array
    {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->list(requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Permanently removes the origin identified by `id`. If the origin is in use by any URL‑endpoints, the API will return an error.
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): mixed {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->delete($id, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Retrieves the origin identified by `id`.
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     *
     * @throws APIException
     */
    public function get(
        string $id,
        ?RequestOptions $requestOptions = null
    ): S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|Gcs|AzureBlob|AkeneoPim {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->get($id, requestOptions: $requestOptions);

        return $response->parse();
    }
}
