<?php

declare(strict_types=1);

namespace Imagekit\Services\Accounts;

use Imagekit\Accounts\Origins\OriginCreateParams;
use Imagekit\Accounts\Origins\OriginResponse;
use Imagekit\Accounts\Origins\OriginResponse\AkeneoPim;
use Imagekit\Accounts\Origins\OriginResponse\AzureBlobStorage;
use Imagekit\Accounts\Origins\OriginResponse\CloudinaryBackup;
use Imagekit\Accounts\Origins\OriginResponse\GoogleCloudStorageGcs;
use Imagekit\Accounts\Origins\OriginResponse\S3;
use Imagekit\Accounts\Origins\OriginResponse\S3Compatible;
use Imagekit\Accounts\Origins\OriginResponse\WebFolder;
use Imagekit\Accounts\Origins\OriginResponse\WebProxy;
use Imagekit\Accounts\Origins\OriginUpdateParams;
use Imagekit\Client;
use Imagekit\Core\Contracts\BaseResponse;
use Imagekit\Core\Conversion\ListOf;
use Imagekit\Core\Exceptions\APIException;
use Imagekit\RequestOptions;
use Imagekit\ServiceContracts\Accounts\OriginsRawContract;

/**
 * @phpstan-import-type RequestOpts from \Imagekit\RequestOptions
 */
final class OriginsRawService implements OriginsRawContract
{
    // @phpstan-ignore-next-line
    /**
     * @internal
     */
    public function __construct(private Client $client) {}

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Creates a new origin and returns the origin object.
     *
     * @param array{
     *   accessKey: string,
     *   bucket: string,
     *   name: string,
     *   secretKey: string,
     *   type?: 'AKENEO_PIM',
     *   baseURLForCanonicalHeader?: string,
     *   includeCanonicalHeader?: bool,
     *   prefix?: string,
     *   endpoint: string,
     *   s3ForcePathStyle?: bool,
     *   baseURL: string,
     *   forwardHostHeaderToOrigin?: bool,
     *   clientEmail: string,
     *   privateKey: string,
     *   accountName: string,
     *   container: string,
     *   sasToken: string,
     *   clientID: string,
     *   clientSecret: string,
     *   password: string,
     *   username: string,
     * }|OriginCreateParams $params
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim,>
     *
     * @throws APIException
     */
    public function create(
        array|OriginCreateParams $params,
        RequestOptions|array|null $requestOptions = null,
    ): BaseResponse {
        [$parsed, $options] = OriginCreateParams::parseRequest(
            $params,
            $requestOptions,
        );

        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'post',
            path: 'v1/accounts/origins',
            body: (object) $parsed,
            options: $options,
            convert: OriginResponse::class,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Updates the origin identified by `id` and returns the updated origin object.
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     * @param array{
     *   accessKey: string,
     *   bucket: string,
     *   name: string,
     *   secretKey: string,
     *   type?: 'AKENEO_PIM',
     *   baseURLForCanonicalHeader?: string,
     *   includeCanonicalHeader?: bool,
     *   prefix?: string,
     *   endpoint: string,
     *   s3ForcePathStyle?: bool,
     *   baseURL: string,
     *   forwardHostHeaderToOrigin?: bool,
     *   clientEmail: string,
     *   privateKey: string,
     *   accountName: string,
     *   container: string,
     *   sasToken: string,
     *   clientID: string,
     *   clientSecret: string,
     *   password: string,
     *   username: string,
     * }|OriginUpdateParams $params
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim,>
     *
     * @throws APIException
     */
    public function update(
        string $id,
        array|OriginUpdateParams $params,
        RequestOptions|array|null $requestOptions = null,
    ): BaseResponse {
        [$parsed, $options] = OriginUpdateParams::parseRequest(
            $params,
            $requestOptions,
        );

        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'put',
            path: ['v1/accounts/origins/%1$s', $id],
            body: (object) $parsed,
            options: $options,
            convert: OriginResponse::class,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Returns an array of all configured origins for the current account.
     *
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<list<S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim>,>
     *
     * @throws APIException
     */
    public function list(
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse {
        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'get',
            path: 'v1/accounts/origins',
            options: $requestOptions,
            convert: new ListOf(OriginResponse::class),
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Permanently removes the origin identified by `id`. If the origin is in use by any URL‑endpoints, the API will return an error.
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<mixed>
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse {
        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'delete',
            path: ['v1/accounts/origins/%1$s', $id],
            options: $requestOptions,
            convert: null,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Retrieves the origin identified by `id`.
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim,>
     *
     * @throws APIException
     */
    public function get(
        string $id,
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse {
        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'get',
            path: ['v1/accounts/origins/%1$s', $id],
            options: $requestOptions,
            convert: OriginResponse::class,
        );
    }
}
