<?php

declare(strict_types=1);

namespace ImageKit\Services\Accounts;

use ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams;
use ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams\URLRewriter\Akamai;
use ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams\URLRewriter\Cloudinary;
use ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams\URLRewriter\Imgix;
use ImageKit\Accounts\URLEndpoints\URLEndpointResponse;
use ImageKit\Accounts\URLEndpoints\URLEndpointUpdateParams;
use ImageKit\Client;
use ImageKit\Core\Conversion\ListOf;
use ImageKit\Core\Exceptions\APIException;
use ImageKit\RequestOptions;
use ImageKit\ServiceContracts\Accounts\URLEndpointsContract;

use const ImageKit\Core\OMIT as omit;

final class URLEndpointsService implements URLEndpointsContract
{
    /**
     * @internal
     */
    public function __construct(private Client $client) {}

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Creates a new URL‑endpoint and returns the resulting object.
     *
     * @param string $description description of the URL endpoint
     * @param list<string> $origins Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     * @param string $urlPrefix path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint)
     * @param Cloudinary|Imgix|Akamai $urlRewriter configuration for third-party URL rewriting
     *
     * @throws APIException
     */
    public function create(
        $description,
        $origins = omit,
        $urlPrefix = omit,
        $urlRewriter = omit,
        ?RequestOptions $requestOptions = null,
    ): URLEndpointResponse {
        $params = [
            'description' => $description,
            'origins' => $origins,
            'urlPrefix' => $urlPrefix,
            'urlRewriter' => $urlRewriter,
        ];

        return $this->createRaw($params, $requestOptions);
    }

    /**
     * @api
     *
     * @param array<string, mixed> $params
     *
     * @throws APIException
     */
    public function createRaw(
        array $params,
        ?RequestOptions $requestOptions = null
    ): URLEndpointResponse {
        [$parsed, $options] = URLEndpointCreateParams::parseRequest(
            $params,
            $requestOptions
        );

        // @phpstan-ignore-next-line;
        return $this->client->request(
            method: 'post',
            path: 'v1/accounts/url-endpoints',
            body: (object) $parsed,
            options: $options,
            convert: URLEndpointResponse::class,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Updates the URL‑endpoint identified by `id` and returns the updated object.
     *
     * @param string $description description of the URL endpoint
     * @param list<string> $origins Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     * @param string $urlPrefix path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint)
     * @param URLEndpointUpdateParams\URLRewriter\Cloudinary|URLEndpointUpdateParams\URLRewriter\Imgix|URLEndpointUpdateParams\URLRewriter\Akamai $urlRewriter configuration for third-party URL rewriting
     *
     * @throws APIException
     */
    public function update(
        string $id,
        $description,
        $origins = omit,
        $urlPrefix = omit,
        $urlRewriter = omit,
        ?RequestOptions $requestOptions = null,
    ): URLEndpointResponse {
        $params = [
            'description' => $description,
            'origins' => $origins,
            'urlPrefix' => $urlPrefix,
            'urlRewriter' => $urlRewriter,
        ];

        return $this->updateRaw($id, $params, $requestOptions);
    }

    /**
     * @api
     *
     * @param array<string, mixed> $params
     *
     * @throws APIException
     */
    public function updateRaw(
        string $id,
        array $params,
        ?RequestOptions $requestOptions = null
    ): URLEndpointResponse {
        [$parsed, $options] = URLEndpointUpdateParams::parseRequest(
            $params,
            $requestOptions
        );

        // @phpstan-ignore-next-line;
        return $this->client->request(
            method: 'put',
            path: ['v1/accounts/url-endpoints/%1$s', $id],
            body: (object) $parsed,
            options: $options,
            convert: URLEndpointResponse::class,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Returns an array of all URL‑endpoints configured including the default URL-endpoint generated by ImageKit during account creation.
     *
     * @return list<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function list(?RequestOptions $requestOptions = null): array
    {
        // @phpstan-ignore-next-line;
        return $this->client->request(
            method: 'get',
            path: 'v1/accounts/url-endpoints',
            options: $requestOptions,
            convert: new ListOf(URLEndpointResponse::class),
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Deletes the URL‑endpoint identified by `id`. You cannot delete the default URL‑endpoint created by ImageKit during account creation.
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): mixed {
        // @phpstan-ignore-next-line;
        return $this->client->request(
            method: 'delete',
            path: ['v1/accounts/url-endpoints/%1$s', $id],
            options: $requestOptions,
            convert: null,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Retrieves the URL‑endpoint identified by `id`.
     *
     * @throws APIException
     */
    public function get(
        string $id,
        ?RequestOptions $requestOptions = null
    ): URLEndpointResponse {
        // @phpstan-ignore-next-line;
        return $this->client->request(
            method: 'get',
            path: ['v1/accounts/url-endpoints/%1$s', $id],
            options: $requestOptions,
            convert: URLEndpointResponse::class,
        );
    }
}
