<?php

declare(strict_types=1);

namespace Imagekit\Services\Accounts;

use Imagekit\Accounts\URLEndpoints\URLEndpointResponse;
use Imagekit\Client;
use Imagekit\Core\Exceptions\APIException;
use Imagekit\RequestOptions;
use Imagekit\ServiceContracts\Accounts\URLEndpointsContract;

final class URLEndpointsService implements URLEndpointsContract
{
    /**
     * @api
     */
    public URLEndpointsRawService $raw;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new URLEndpointsRawService($client);
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Creates a new URL‑endpoint and returns the resulting object.
     *
     * @param string $description description of the URL endpoint
     * @param list<string> $origins Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     * @param string $urlPrefix path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint)
     * @param array<string,mixed> $urlRewriter configuration for third-party URL rewriting
     *
     * @throws APIException
     */
    public function create(
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        ?array $urlRewriter = null,
        ?RequestOptions $requestOptions = null,
    ): URLEndpointResponse {
        $params = [
            'description' => $description,
            'origins' => $origins,
            'urlPrefix' => $urlPrefix,
            'urlRewriter' => $urlRewriter,
        ];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->create(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Updates the URL‑endpoint identified by `id` and returns the updated object.
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param string $description description of the URL endpoint
     * @param list<string> $origins Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     * @param string $urlPrefix path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint)
     * @param array<string,mixed> $urlRewriter configuration for third-party URL rewriting
     *
     * @throws APIException
     */
    public function update(
        string $id,
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        ?array $urlRewriter = null,
        ?RequestOptions $requestOptions = null,
    ): URLEndpointResponse {
        $params = [
            'description' => $description,
            'origins' => $origins,
            'urlPrefix' => $urlPrefix,
            'urlRewriter' => $urlRewriter,
        ];
        // @phpstan-ignore-next-line function.impossibleType
        $params = array_filter($params, callback: static fn ($v) => !is_null($v));

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->update($id, params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Returns an array of all URL‑endpoints configured including the default URL-endpoint generated by ImageKit during account creation.
     *
     * @return list<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function list(?RequestOptions $requestOptions = null): array
    {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->list(requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Deletes the URL‑endpoint identified by `id`. You cannot delete the default URL‑endpoint created by ImageKit during account creation.
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): mixed {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->delete($id, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Retrieves the URL‑endpoint identified by `id`.
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     *
     * @throws APIException
     */
    public function get(
        string $id,
        ?RequestOptions $requestOptions = null
    ): URLEndpointResponse {
        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->get($id, requestOptions: $requestOptions);

        return $response->parse();
    }
}
