<?php

declare(strict_types=1);

namespace ImageKit\Services\Accounts;

use ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams;
use ImageKit\Accounts\URLEndpoints\URLEndpointResponse;
use ImageKit\Accounts\URLEndpoints\URLEndpointUpdateParams;
use ImageKit\Client;
use ImageKit\Core\Contracts\BaseResponse;
use ImageKit\Core\Conversion\ListOf;
use ImageKit\Core\Exceptions\APIException;
use ImageKit\RequestOptions;
use ImageKit\ServiceContracts\Accounts\URLEndpointsRawContract;

/**
 * @phpstan-import-type URLRewriterShape from \ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams\URLRewriter
 * @phpstan-import-type URLRewriterShape from \ImageKit\Accounts\URLEndpoints\URLEndpointUpdateParams\URLRewriter as URLRewriterShape1
 * @phpstan-import-type RequestOpts from \ImageKit\RequestOptions
 */
final class URLEndpointsRawService implements URLEndpointsRawContract
{
    // @phpstan-ignore-next-line
    /**
     * @internal
     */
    public function __construct(private Client $client) {}

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Creates a new URL‑endpoint and returns the resulting object.
     *
     * @param array{
     *   description: string,
     *   origins?: list<string>,
     *   urlPrefix?: string,
     *   urlRewriter?: URLRewriterShape,
     * }|URLEndpointCreateParams $params
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function create(
        array|URLEndpointCreateParams $params,
        RequestOptions|array|null $requestOptions = null,
    ): BaseResponse {
        [$parsed, $options] = URLEndpointCreateParams::parseRequest(
            $params,
            $requestOptions,
        );

        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'post',
            path: 'v2/accounts/url-endpoints',
            body: (object) $parsed,
            options: $options,
            convert: URLEndpointResponse::class,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Updates the URL‑endpoint identified by `id` and returns the updated object.
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param array{
     *   description: string,
     *   origins?: list<string>,
     *   urlPrefix?: string,
     *   urlRewriter?: URLRewriterShape1,
     * }|URLEndpointUpdateParams $params
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function update(
        string $id,
        array|URLEndpointUpdateParams $params,
        RequestOptions|array|null $requestOptions = null,
    ): BaseResponse {
        [$parsed, $options] = URLEndpointUpdateParams::parseRequest(
            $params,
            $requestOptions,
        );

        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'put',
            path: ['v2/accounts/url-endpoints/%1$s', $id],
            body: (object) $parsed,
            options: $options,
            convert: URLEndpointResponse::class,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Returns an array of all URL‑endpoints configured including the default URL-endpoint generated by ImageKit during account creation.
     *
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<list<URLEndpointResponse>>
     *
     * @throws APIException
     */
    public function list(
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse {
        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'get',
            path: 'v2/accounts/url-endpoints',
            options: $requestOptions,
            convert: new ListOf(URLEndpointResponse::class),
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Deletes the URL‑endpoint identified by `id`. You cannot delete the default URL‑endpoint created by ImageKit during account creation.
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<mixed>
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse {
        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'delete',
            path: ['v2/accounts/url-endpoints/%1$s', $id],
            options: $requestOptions,
            convert: null,
        );
    }

    /**
     * @api
     *
     * **Note:** This API is currently in beta.
     * Retrieves the URL‑endpoint identified by `id`.
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function get(
        string $id,
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse {
        // @phpstan-ignore-next-line return.type
        return $this->client->request(
            method: 'get',
            path: ['v2/accounts/url-endpoints/%1$s', $id],
            options: $requestOptions,
            convert: URLEndpointResponse::class,
        );
    }
}
