<?php

declare(strict_types=1);

namespace ImageKit\Responses\Accounts\URLEndpoints;

use ImageKit\Core\Attributes\Api;
use ImageKit\Core\Concerns\Model;
use ImageKit\Core\Contracts\BaseModel;
use ImageKit\Core\Conversion\ListOf;
use ImageKit\Responses\Accounts\URLEndpoints\URLEndpointGetResponse\URLRewriter\AkamaiURLRewriter;
use ImageKit\Responses\Accounts\URLEndpoints\URLEndpointGetResponse\URLRewriter\CloudinaryURLRewriter;
use ImageKit\Responses\Accounts\URLEndpoints\URLEndpointGetResponse\URLRewriter\ImgixURLRewriter;

/**
 * URL‑endpoint object as returned by the API.
 *
 * @phpstan-type url_endpoint_get_response_alias = array{
 *   id: string,
 *   description: string,
 *   origins: list<string>,
 *   urlPrefix: string,
 *   urlRewriter?: CloudinaryURLRewriter|ImgixURLRewriter|AkamaiURLRewriter,
 * }
 */
final class URLEndpointGetResponse implements BaseModel
{
    use Model;

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    #[Api]
    public string $id;

    /**
     * Description of the URL endpoint.
     */
    #[Api]
    public string $description;

    /**
     * Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     *
     * @var list<string> $origins
     */
    #[Api(type: new ListOf('string'))]
    public array $origins;

    /**
     * Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).
     */
    #[Api]
    public string $urlPrefix;

    /**
     * Configuration for third-party URL rewriting.
     */
    #[Api(optional: true)]
    public null|AkamaiURLRewriter|CloudinaryURLRewriter|ImgixURLRewriter $urlRewriter;

    /**
     * `new URLEndpointGetResponse()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * URLEndpointGetResponse::with(
     *   id: ..., description: ..., origins: ..., urlPrefix: ...
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new URLEndpointGetResponse)
     *   ->withID(...)
     *   ->withDescription(...)
     *   ->withOrigins(...)
     *   ->withURLPrefix(...)
     * ```
     */
    public function __construct()
    {
        self::introspect();
        $this->unsetOptionalProperties();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<string> $origins
     */
    public static function with(
        string $id,
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        null|AkamaiURLRewriter|CloudinaryURLRewriter|ImgixURLRewriter $urlRewriter = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->description = $description;
        $obj->origins = $origins;
        $obj->urlPrefix = $urlPrefix;

        null !== $urlRewriter && $obj->urlRewriter = $urlRewriter;

        return $obj;
    }

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    /**
     * Description of the URL endpoint.
     */
    public function withDescription(string $description): self
    {
        $obj = clone $this;
        $obj->description = $description;

        return $obj;
    }

    /**
     * Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     *
     * @param list<string> $origins
     */
    public function withOrigins(array $origins): self
    {
        $obj = clone $this;
        $obj->origins = $origins;

        return $obj;
    }

    /**
     * Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).
     */
    public function withURLPrefix(string $urlPrefix): self
    {
        $obj = clone $this;
        $obj->urlPrefix = $urlPrefix;

        return $obj;
    }

    /**
     * Configuration for third-party URL rewriting.
     */
    public function withURLRewriter(
        AkamaiURLRewriter|CloudinaryURLRewriter|ImgixURLRewriter $urlRewriter
    ): self {
        $obj = clone $this;
        $obj->urlRewriter = $urlRewriter;

        return $obj;
    }
}
