<?php

declare(strict_types=1);

namespace Imagekit\ServiceContracts\Accounts;

use Imagekit\Accounts\Origins\OriginResponse\AkeneoPim;
use Imagekit\Accounts\Origins\OriginResponse\AzureBlobStorage;
use Imagekit\Accounts\Origins\OriginResponse\CloudinaryBackup;
use Imagekit\Accounts\Origins\OriginResponse\GoogleCloudStorageGcs;
use Imagekit\Accounts\Origins\OriginResponse\S3;
use Imagekit\Accounts\Origins\OriginResponse\S3Compatible;
use Imagekit\Accounts\Origins\OriginResponse\WebFolder;
use Imagekit\Accounts\Origins\OriginResponse\WebProxy;
use Imagekit\Core\Exceptions\APIException;
use Imagekit\RequestOptions;

interface OriginsContract
{
    /**
     * @api
     *
     * @param string $accessKey access key for the bucket
     * @param string $name display name of the origin
     * @param string $secretKey secret key for the bucket
     * @param string $endpoint custom S3-compatible endpoint
     * @param string $baseURL akeneo instance base URL
     * @param string $clientID akeneo API client ID
     * @param string $clientSecret akeneo API client secret
     * @param string $password akeneo API password
     * @param string $username akeneo API username
     * @param 'AKENEO_PIM' $type
     * @param string $baseURLForCanonicalHeader URL used in the Canonical header (if enabled)
     * @param bool $includeCanonicalHeader whether to send a Canonical header
     * @param bool $s3ForcePathStyle Use path-style S3 URLs?
     * @param bool $forwardHostHeaderToOrigin Forward the Host header to origin?
     *
     * @throws APIException
     */
    public function create(
        string $accessKey,
        string $bucket,
        string $name,
        string $secretKey,
        string $endpoint,
        string $baseURL,
        string $clientEmail,
        string $privateKey,
        string $accountName,
        string $container,
        string $sasToken,
        string $clientID,
        string $clientSecret,
        string $password,
        string $username,
        string $type = 'AKENEO_PIM',
        ?string $baseURLForCanonicalHeader = null,
        bool $includeCanonicalHeader = false,
        string $prefix = '',
        bool $s3ForcePathStyle = false,
        bool $forwardHostHeaderToOrigin = false,
        ?RequestOptions $requestOptions = null,
    ): S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim;

    /**
     * @api
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     * @param string $accessKey access key for the bucket
     * @param string $name display name of the origin
     * @param string $secretKey secret key for the bucket
     * @param string $endpoint custom S3-compatible endpoint
     * @param string $baseURL akeneo instance base URL
     * @param string $clientID akeneo API client ID
     * @param string $clientSecret akeneo API client secret
     * @param string $password akeneo API password
     * @param string $username akeneo API username
     * @param 'AKENEO_PIM' $type
     * @param string $baseURLForCanonicalHeader URL used in the Canonical header (if enabled)
     * @param bool $includeCanonicalHeader whether to send a Canonical header
     * @param bool $s3ForcePathStyle Use path-style S3 URLs?
     * @param bool $forwardHostHeaderToOrigin Forward the Host header to origin?
     *
     * @throws APIException
     */
    public function update(
        string $id,
        string $accessKey,
        string $bucket,
        string $name,
        string $secretKey,
        string $endpoint,
        string $baseURL,
        string $clientEmail,
        string $privateKey,
        string $accountName,
        string $container,
        string $sasToken,
        string $clientID,
        string $clientSecret,
        string $password,
        string $username,
        string $type = 'AKENEO_PIM',
        ?string $baseURLForCanonicalHeader = null,
        bool $includeCanonicalHeader = false,
        string $prefix = '',
        bool $s3ForcePathStyle = false,
        bool $forwardHostHeaderToOrigin = false,
        ?RequestOptions $requestOptions = null,
    ): S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim;

    /**
     * @api
     *
     * @return list<S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim>
     *
     * @throws APIException
     */
    public function list(?RequestOptions $requestOptions = null): array;

    /**
     * @api
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): mixed;

    /**
     * @api
     *
     * @param string $id Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     *
     * @throws APIException
     */
    public function get(
        string $id,
        ?RequestOptions $requestOptions = null
    ): S3|S3Compatible|CloudinaryBackup|WebFolder|WebProxy|GoogleCloudStorageGcs|AzureBlobStorage|AkeneoPim;
}
