<?php

declare(strict_types=1);

namespace Imagekit\ServiceContracts\Accounts;

use Imagekit\Accounts\URLEndpoints\URLEndpointCreateParams;
use Imagekit\Accounts\URLEndpoints\URLEndpointResponse;
use Imagekit\Accounts\URLEndpoints\URLEndpointUpdateParams;
use Imagekit\Core\Contracts\BaseResponse;
use Imagekit\Core\Exceptions\APIException;
use Imagekit\RequestOptions;

interface URLEndpointsRawContract
{
    /**
     * @api
     *
     * @param array<mixed>|URLEndpointCreateParams $params
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function create(
        array|URLEndpointCreateParams $params,
        ?RequestOptions $requestOptions = null,
    ): BaseResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param array<mixed>|URLEndpointUpdateParams $params
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function update(
        string $id,
        array|URLEndpointUpdateParams $params,
        ?RequestOptions $requestOptions = null,
    ): BaseResponse;

    /**
     * @api
     *
     * @return BaseResponse<list<URLEndpointResponse>>
     *
     * @throws APIException
     */
    public function list(?RequestOptions $requestOptions = null): BaseResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     *
     * @return BaseResponse<mixed>
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): BaseResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function get(
        string $id,
        ?RequestOptions $requestOptions = null
    ): BaseResponse;
}
