<?php

declare(strict_types=1);

namespace ImageKit\ServiceContracts\Accounts;

use ImageKit\Accounts\URLEndpoints\URLEndpointCreateParams;
use ImageKit\Accounts\URLEndpoints\URLEndpointResponse;
use ImageKit\Accounts\URLEndpoints\URLEndpointUpdateParams;
use ImageKit\Core\Contracts\BaseResponse;
use ImageKit\Core\Exceptions\APIException;
use ImageKit\RequestOptions;

/**
 * @phpstan-import-type RequestOpts from \ImageKit\RequestOptions
 */
interface URLEndpointsRawContract
{
    /**
     * @api
     *
     * @param array<string,mixed>|URLEndpointCreateParams $params
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function create(
        array|URLEndpointCreateParams $params,
        RequestOptions|array|null $requestOptions = null,
    ): BaseResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param array<string,mixed>|URLEndpointUpdateParams $params
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function update(
        string $id,
        array|URLEndpointUpdateParams $params,
        RequestOptions|array|null $requestOptions = null,
    ): BaseResponse;

    /**
     * @api
     *
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<list<URLEndpointResponse>>
     *
     * @throws APIException
     */
    public function list(
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<mixed>
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param RequestOpts|null $requestOptions
     *
     * @return BaseResponse<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function get(
        string $id,
        RequestOptions|array|null $requestOptions = null
    ): BaseResponse;
}
