<?php

declare(strict_types=1);

namespace Imagekit\ServiceContracts\Accounts;

use Imagekit\Accounts\URLEndpoints\URLEndpointResponse;
use Imagekit\Core\Exceptions\APIException;
use Imagekit\RequestOptions;

interface URLEndpointsContract
{
    /**
     * @api
     *
     * @param string $description description of the URL endpoint
     * @param list<string> $origins Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     * @param string $urlPrefix path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint)
     * @param array<string,mixed> $urlRewriter configuration for third-party URL rewriting
     *
     * @throws APIException
     */
    public function create(
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        ?array $urlRewriter = null,
        ?RequestOptions $requestOptions = null,
    ): URLEndpointResponse;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     * @param string $description description of the URL endpoint
     * @param list<string> $origins Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.
     * @param string $urlPrefix path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint)
     * @param array<string,mixed> $urlRewriter configuration for third-party URL rewriting
     *
     * @throws APIException
     */
    public function update(
        string $id,
        string $description,
        array $origins = [],
        string $urlPrefix = '',
        ?array $urlRewriter = null,
        ?RequestOptions $requestOptions = null,
    ): URLEndpointResponse;

    /**
     * @api
     *
     * @return list<URLEndpointResponse>
     *
     * @throws APIException
     */
    public function list(?RequestOptions $requestOptions = null): array;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     *
     * @throws APIException
     */
    public function delete(
        string $id,
        ?RequestOptions $requestOptions = null
    ): mixed;

    /**
     * @api
     *
     * @param string $id Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
     *
     * @throws APIException
     */
    public function get(
        string $id,
        ?RequestOptions $requestOptions = null
    ): URLEndpointResponse;
}
