<?php

declare(strict_types=1);

namespace ImageKit\Accounts\Origins\OriginResponse;

use ImageKit\Core\Attributes\Api;
use ImageKit\Core\Concerns\SdkModel;
use ImageKit\Core\Contracts\BaseModel;

/**
 * @phpstan-type AkeneoPimShape = array{
 *   id: string,
 *   baseUrl: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   type: 'AKENEO_PIM',
 *   baseUrlForCanonicalHeader?: string|null,
 * }
 */
final class AkeneoPim implements BaseModel
{
    /** @use SdkModel<AkeneoPimShape> */
    use SdkModel;

    /** @var 'AKENEO_PIM' $type */
    #[Api]
    public string $type = 'AKENEO_PIM';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Api]
    public string $id;

    /**
     * Akeneo instance base URL.
     */
    #[Api]
    public string $baseUrl;

    /**
     * Whether to send a Canonical header.
     */
    #[Api]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Api]
    public string $name;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Api(optional: true)]
    public ?string $baseUrlForCanonicalHeader;

    /**
     * `new AkeneoPim()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * AkeneoPim::with(id: ..., baseUrl: ..., includeCanonicalHeader: ..., name: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new AkeneoPim)
     *   ->withID(...)
     *   ->withBaseURL(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $baseUrl,
        string $name,
        bool $includeCanonicalHeader = false,
        ?string $baseUrlForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->baseUrl = $baseUrl;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;
        $obj->name = $name;

        null !== $baseUrlForCanonicalHeader && $obj->baseUrlForCanonicalHeader = $baseUrlForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    /**
     * Akeneo instance base URL.
     */
    public function withBaseURL(string $baseURL): self
    {
        $obj = clone $this;
        $obj->baseUrl = $baseURL;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->includeCanonicalHeader = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj->name = $name;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj->baseUrlForCanonicalHeader = $baseURLForCanonicalHeader;

        return $obj;
    }
}
