<?php

declare(strict_types=1);

namespace Imagekit\Accounts\Origins\OriginResponse;

use Imagekit\Core\Attributes\Optional;
use Imagekit\Core\Attributes\Required;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * @phpstan-type AkeneoPimShape = array{
 *   id: string,
 *   baseURL: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   type?: 'AKENEO_PIM',
 *   baseURLForCanonicalHeader?: string|null,
 * }
 */
final class AkeneoPim implements BaseModel
{
    /** @use SdkModel<AkeneoPimShape> */
    use SdkModel;

    /** @var 'AKENEO_PIM' $type */
    #[Required]
    public string $type = 'AKENEO_PIM';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Required]
    public string $id;

    /**
     * Akeneo instance base URL.
     */
    #[Required('baseUrl')]
    public string $baseURL;

    /**
     * Whether to send a Canonical header.
     */
    #[Required]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Required]
    public string $name;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Optional('baseUrlForCanonicalHeader')]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new AkeneoPim()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * AkeneoPim::with(id: ..., baseURL: ..., includeCanonicalHeader: ..., name: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new AkeneoPim)
     *   ->withID(...)
     *   ->withBaseURL(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $baseURL,
        string $name,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['baseURL'] = $baseURL;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;
        $self['name'] = $name;

        null !== $baseURLForCanonicalHeader && $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Akeneo instance base URL.
     */
    public function withBaseURL(string $baseURL): self
    {
        $self = clone $this;
        $self['baseURL'] = $baseURL;

        return $self;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $self = clone $this;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $self;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $self = clone $this;
        $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }
}
