<?php

declare(strict_types=1);

namespace Imagekit\Accounts\Origins\OriginResponse;

use Imagekit\Core\Attributes\Api;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * @phpstan-type AzureBlobShape = array{
 *   id: string,
 *   accountName: string,
 *   container: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   type: 'AZURE_BLOB',
 *   baseUrlForCanonicalHeader?: string|null,
 * }
 */
final class AzureBlob implements BaseModel
{
    /** @use SdkModel<AzureBlobShape> */
    use SdkModel;

    /** @var 'AZURE_BLOB' $type */
    #[Api]
    public string $type = 'AZURE_BLOB';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Api]
    public string $id;

    #[Api]
    public string $accountName;

    #[Api]
    public string $container;

    /**
     * Whether to send a Canonical header.
     */
    #[Api]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Api]
    public string $name;

    #[Api]
    public string $prefix;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Api(optional: true)]
    public ?string $baseUrlForCanonicalHeader;

    /**
     * `new AzureBlob()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * AzureBlob::with(
     *   id: ...,
     *   accountName: ...,
     *   container: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   prefix: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new AzureBlob)
     *   ->withID(...)
     *   ->withAccountName(...)
     *   ->withContainer(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $accountName,
        string $container,
        string $name,
        string $prefix,
        bool $includeCanonicalHeader = false,
        ?string $baseUrlForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj['id'] = $id;
        $obj['accountName'] = $accountName;
        $obj['container'] = $container;
        $obj['includeCanonicalHeader'] = $includeCanonicalHeader;
        $obj['name'] = $name;
        $obj['prefix'] = $prefix;

        null !== $baseUrlForCanonicalHeader && $obj['baseUrlForCanonicalHeader'] = $baseUrlForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    public function withAccountName(string $accountName): self
    {
        $obj = clone $this;
        $obj['accountName'] = $accountName;

        return $obj;
    }

    public function withContainer(string $container): self
    {
        $obj = clone $this;
        $obj['container'] = $container;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj['name'] = $name;

        return $obj;
    }

    public function withPrefix(string $prefix): self
    {
        $obj = clone $this;
        $obj['prefix'] = $prefix;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj['baseUrlForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $obj;
    }
}
