<?php

declare(strict_types=1);

namespace ImageKit\Accounts\Origins\OriginResponse;

use ImageKit\Core\Attributes\Optional;
use ImageKit\Core\Attributes\Required;
use ImageKit\Core\Concerns\SdkModel;
use ImageKit\Core\Contracts\BaseModel;

/**
 * @phpstan-type CloudinaryBackupShape = array{
 *   id: string,
 *   bucket: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   type: 'CLOUDINARY_BACKUP',
 *   baseURLForCanonicalHeader?: string|null,
 * }
 */
final class CloudinaryBackup implements BaseModel
{
    /** @use SdkModel<CloudinaryBackupShape> */
    use SdkModel;

    /** @var 'CLOUDINARY_BACKUP' $type */
    #[Required]
    public string $type = 'CLOUDINARY_BACKUP';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Required]
    public string $id;

    /**
     * S3 bucket name.
     */
    #[Required]
    public string $bucket;

    /**
     * Whether to send a Canonical header.
     */
    #[Required('include_canonical_header')]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Required]
    public string $name;

    /**
     * Path prefix inside the bucket.
     */
    #[Required]
    public string $prefix;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Optional('base_url_for_canonical_header')]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new CloudinaryBackup()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * CloudinaryBackup::with(
     *   id: ..., bucket: ..., includeCanonicalHeader: ..., name: ..., prefix: ...
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new CloudinaryBackup)
     *   ->withID(...)
     *   ->withBucket(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $bucket,
        string $name,
        string $prefix,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['bucket'] = $bucket;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;
        $self['name'] = $name;
        $self['prefix'] = $prefix;

        null !== $baseURLForCanonicalHeader && $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * S3 bucket name.
     */
    public function withBucket(string $bucket): self
    {
        $self = clone $this;
        $self['bucket'] = $bucket;

        return $self;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $self = clone $this;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $self;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }

    /**
     * Path prefix inside the bucket.
     */
    public function withPrefix(string $prefix): self
    {
        $self = clone $this;
        $self['prefix'] = $prefix;

        return $self;
    }

    /**
     * @param 'CLOUDINARY_BACKUP' $type
     */
    public function withType(string $type): self
    {
        $self = clone $this;
        $self['type'] = $type;

        return $self;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $self = clone $this;
        $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }
}
