<?php

declare(strict_types=1);

namespace Imagekit\Accounts\Origins\OriginResponse;

use Imagekit\Core\Attributes\Optional;
use Imagekit\Core\Attributes\Required;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * @phpstan-type GcsShape = array{
 *   id: string,
 *   bucket: string,
 *   clientEmail: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   type?: 'GCS',
 *   baseUrlForCanonicalHeader?: string|null,
 * }
 */
final class Gcs implements BaseModel
{
    /** @use SdkModel<GcsShape> */
    use SdkModel;

    /** @var 'GCS' $type */
    #[Required]
    public string $type = 'GCS';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Required]
    public string $id;

    #[Required]
    public string $bucket;

    #[Required]
    public string $clientEmail;

    /**
     * Whether to send a Canonical header.
     */
    #[Required]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Required]
    public string $name;

    #[Required]
    public string $prefix;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Optional]
    public ?string $baseUrlForCanonicalHeader;

    /**
     * `new Gcs()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Gcs::with(
     *   id: ...,
     *   bucket: ...,
     *   clientEmail: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   prefix: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Gcs)
     *   ->withID(...)
     *   ->withBucket(...)
     *   ->withClientEmail(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $bucket,
        string $clientEmail,
        string $name,
        string $prefix,
        bool $includeCanonicalHeader = false,
        ?string $baseUrlForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj['id'] = $id;
        $obj['bucket'] = $bucket;
        $obj['clientEmail'] = $clientEmail;
        $obj['includeCanonicalHeader'] = $includeCanonicalHeader;
        $obj['name'] = $name;
        $obj['prefix'] = $prefix;

        null !== $baseUrlForCanonicalHeader && $obj['baseUrlForCanonicalHeader'] = $baseUrlForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    public function withBucket(string $bucket): self
    {
        $obj = clone $this;
        $obj['bucket'] = $bucket;

        return $obj;
    }

    public function withClientEmail(string $clientEmail): self
    {
        $obj = clone $this;
        $obj['clientEmail'] = $clientEmail;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj['name'] = $name;

        return $obj;
    }

    public function withPrefix(string $prefix): self
    {
        $obj = clone $this;
        $obj['prefix'] = $prefix;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj['baseUrlForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $obj;
    }
}
