<?php

declare(strict_types=1);

namespace Imagekit\Accounts\Origins\OriginResponse;

use Imagekit\Core\Attributes\Optional;
use Imagekit\Core\Attributes\Required;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * @phpstan-type S3CompatibleShape = array{
 *   id: string,
 *   bucket: string,
 *   endpoint: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   prefix: string,
 *   s3ForcePathStyle: bool,
 *   type: 'S3_COMPATIBLE',
 *   baseURLForCanonicalHeader?: string|null,
 * }
 */
final class S3Compatible implements BaseModel
{
    /** @use SdkModel<S3CompatibleShape> */
    use SdkModel;

    /** @var 'S3_COMPATIBLE' $type */
    #[Required]
    public string $type = 'S3_COMPATIBLE';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Required]
    public string $id;

    /**
     * S3 bucket name.
     */
    #[Required]
    public string $bucket;

    /**
     * Custom S3-compatible endpoint.
     */
    #[Required]
    public string $endpoint;

    /**
     * Whether to send a Canonical header.
     */
    #[Required]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Required]
    public string $name;

    /**
     * Path prefix inside the bucket.
     */
    #[Required]
    public string $prefix;

    /**
     * Use path-style S3 URLs?
     */
    #[Required]
    public bool $s3ForcePathStyle;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Optional('baseUrlForCanonicalHeader')]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new S3Compatible()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * S3Compatible::with(
     *   id: ...,
     *   bucket: ...,
     *   endpoint: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     *   prefix: ...,
     *   s3ForcePathStyle: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new S3Compatible)
     *   ->withID(...)
     *   ->withBucket(...)
     *   ->withEndpoint(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     *   ->withPrefix(...)
     *   ->withS3ForcePathStyle(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $bucket,
        string $endpoint,
        string $name,
        string $prefix,
        bool $includeCanonicalHeader = false,
        bool $s3ForcePathStyle = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['bucket'] = $bucket;
        $self['endpoint'] = $endpoint;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;
        $self['name'] = $name;
        $self['prefix'] = $prefix;
        $self['s3ForcePathStyle'] = $s3ForcePathStyle;

        null !== $baseURLForCanonicalHeader && $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * S3 bucket name.
     */
    public function withBucket(string $bucket): self
    {
        $self = clone $this;
        $self['bucket'] = $bucket;

        return $self;
    }

    /**
     * Custom S3-compatible endpoint.
     */
    public function withEndpoint(string $endpoint): self
    {
        $self = clone $this;
        $self['endpoint'] = $endpoint;

        return $self;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $self = clone $this;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $self;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }

    /**
     * Path prefix inside the bucket.
     */
    public function withPrefix(string $prefix): self
    {
        $self = clone $this;
        $self['prefix'] = $prefix;

        return $self;
    }

    /**
     * Use path-style S3 URLs?
     */
    public function withS3ForcePathStyle(bool $s3ForcePathStyle): self
    {
        $self = clone $this;
        $self['s3ForcePathStyle'] = $s3ForcePathStyle;

        return $self;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $self = clone $this;
        $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }
}
