<?php

declare(strict_types=1);

namespace Imagekit\Accounts\Origins\OriginResponse;

use Imagekit\Core\Attributes\Optional;
use Imagekit\Core\Attributes\Required;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * @phpstan-type WebFolderShape = array{
 *   id: string,
 *   baseURL: string,
 *   forwardHostHeaderToOrigin: bool,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   type: 'WEB_FOLDER',
 *   baseURLForCanonicalHeader?: string|null,
 * }
 */
final class WebFolder implements BaseModel
{
    /** @use SdkModel<WebFolderShape> */
    use SdkModel;

    /** @var 'WEB_FOLDER' $type */
    #[Required]
    public string $type = 'WEB_FOLDER';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Required]
    public string $id;

    /**
     * Root URL for the web folder origin.
     */
    #[Required('baseUrl')]
    public string $baseURL;

    /**
     * Forward the Host header to origin?
     */
    #[Required]
    public bool $forwardHostHeaderToOrigin;

    /**
     * Whether to send a Canonical header.
     */
    #[Required]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Required]
    public string $name;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Optional('baseUrlForCanonicalHeader')]
    public ?string $baseURLForCanonicalHeader;

    /**
     * `new WebFolder()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * WebFolder::with(
     *   id: ...,
     *   baseURL: ...,
     *   forwardHostHeaderToOrigin: ...,
     *   includeCanonicalHeader: ...,
     *   name: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new WebFolder)
     *   ->withID(...)
     *   ->withBaseURL(...)
     *   ->withForwardHostHeaderToOrigin(...)
     *   ->withIncludeCanonicalHeader(...)
     *   ->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $baseURL,
        string $name,
        bool $forwardHostHeaderToOrigin = false,
        bool $includeCanonicalHeader = false,
        ?string $baseURLForCanonicalHeader = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['baseURL'] = $baseURL;
        $self['forwardHostHeaderToOrigin'] = $forwardHostHeaderToOrigin;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;
        $self['name'] = $name;

        null !== $baseURLForCanonicalHeader && $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Root URL for the web folder origin.
     */
    public function withBaseURL(string $baseURL): self
    {
        $self = clone $this;
        $self['baseURL'] = $baseURL;

        return $self;
    }

    /**
     * Forward the Host header to origin?
     */
    public function withForwardHostHeaderToOrigin(
        bool $forwardHostHeaderToOrigin
    ): self {
        $self = clone $this;
        $self['forwardHostHeaderToOrigin'] = $forwardHostHeaderToOrigin;

        return $self;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $self = clone $this;
        $self['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $self;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $self = clone $this;
        $self['baseURLForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $self;
    }
}
