<?php

declare(strict_types=1);

namespace Imagekit\Accounts\Origins\OriginResponse;

use Imagekit\Core\Attributes\Optional;
use Imagekit\Core\Attributes\Required;
use Imagekit\Core\Concerns\SdkModel;
use Imagekit\Core\Contracts\BaseModel;

/**
 * @phpstan-type WebProxyShape = array{
 *   id: string,
 *   includeCanonicalHeader: bool,
 *   name: string,
 *   type: 'WEB_PROXY',
 *   baseUrlForCanonicalHeader?: string|null,
 * }
 */
final class WebProxy implements BaseModel
{
    /** @use SdkModel<WebProxyShape> */
    use SdkModel;

    /** @var 'WEB_PROXY' $type */
    #[Required]
    public string $type = 'WEB_PROXY';

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    #[Required]
    public string $id;

    /**
     * Whether to send a Canonical header.
     */
    #[Required]
    public bool $includeCanonicalHeader;

    /**
     * Display name of the origin.
     */
    #[Required]
    public string $name;

    /**
     * URL used in the Canonical header (if enabled).
     */
    #[Optional]
    public ?string $baseUrlForCanonicalHeader;

    /**
     * `new WebProxy()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * WebProxy::with(id: ..., includeCanonicalHeader: ..., name: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new WebProxy)->withID(...)->withIncludeCanonicalHeader(...)->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $name,
        bool $includeCanonicalHeader = false,
        ?string $baseUrlForCanonicalHeader = null,
    ): self {
        $obj = new self;

        $obj['id'] = $id;
        $obj['includeCanonicalHeader'] = $includeCanonicalHeader;
        $obj['name'] = $name;

        null !== $baseUrlForCanonicalHeader && $obj['baseUrlForCanonicalHeader'] = $baseUrlForCanonicalHeader;

        return $obj;
    }

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    /**
     * Whether to send a Canonical header.
     */
    public function withIncludeCanonicalHeader(
        bool $includeCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj['includeCanonicalHeader'] = $includeCanonicalHeader;

        return $obj;
    }

    /**
     * Display name of the origin.
     */
    public function withName(string $name): self
    {
        $obj = clone $this;
        $obj['name'] = $name;

        return $obj;
    }

    /**
     * URL used in the Canonical header (if enabled).
     */
    public function withBaseURLForCanonicalHeader(
        string $baseURLForCanonicalHeader
    ): self {
        $obj = clone $this;
        $obj['baseUrlForCanonicalHeader'] = $baseURLForCanonicalHeader;

        return $obj;
    }
}
