name: CI
on:
  push:
    branches:
      - '**'
      - '!integrated/**'
      - '!stl-preview-head/**'
      - '!stl-preview-base/**'
      - '!generated'
      - '!codegen/**'
      - 'codegen/stl/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    runs-on: ${{ github.repository == 'stainless-sdks/imagekit-php' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork

    steps:
      - uses: actions/checkout@v6

      - name: Set up PHP
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.3'

      - name: Run Bootstrap
        run: ./scripts/bootstrap

      - name: Run lints
        run: ./scripts/lint
  test:
    timeout-minutes: 10
    name: test
    runs-on: ${{ github.repository == 'stainless-sdks/imagekit-php' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - name: Set up PHP
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.3'

      - name: Run bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test
